### ISSUE TITLE
On left speaker bug

### ISSUE THREAD

**Issue by b1mt3** [SonyAosp/platform_vendor_sonyaosp#2]
**Platform: tone** 
**Device: dora** 
**Kernel version: 4.9** 
**Android version: 8.1** 

**Description**
Left speaker is not working until making a call

**Symptoms**
Testing via StereoTest, left speaker doesn't produce a sound

**How to reproduce**
Install "Left Right Stereo Test", start testing - left speaker doesn't work.
Make a call so to activate the earphone (I check Voicemail), then get back into Stereo Test application - left speaker works.

Will try to provide a relevant snippet of `adb logcat` later.

**Comment by alviteri** [comment]
Hi @b1mt3 thanks for your report ... can you please report this in official sony git development site ... thank you

https://github.com/sonyxperiadev/bug_tracker
